### ISSUE TITLE
expect(object).to.be.an('object') failing with 'ReferenceError: HTMLElement is not defined'

### ISSUE THREAD

**Issue by john681611** [chaijs/chai#1029]
Object: 
```
{ matches: [Getter],
  media: [Getter],
  addListener: [Function: addListener],
  removeListener: [Function: removeListener] }
```
though can use {}

code snippet
```
let matcher = matchMedia(ViewPort.sm);
expect(matcher).to.be.an('object');
```

error:
```
 ReferenceError: HTMLElement is not defined
      at Object.typeDetect [as type] (node_modules/type-detect/index.js:163:24)
      at Proxy.an (node_modules/chai/lib/chai/core/assertions.js:306:20)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:272:28)
      at Proxy.overwritingChainableMethodWrapper (node_modules/chai/lib/chai/utils/overwriteChainableMethod.js:60:34)
      at Proxy.chainableMethodWrapper (node_modules/chai/lib/chai/utils/addChainableMethod.js:113:49)
      at Context.<anonymous> (src/client/common/matchMedia.test.js:16:31)

```

**Comment by keithamus** [comment]
Thanks for the issue @john681611 

We have a PR ready to merge for this [here](https://github.com/chaijs/type-detect/pull/91). It needs some small updates but will hopefully be ready soon enough.

**Comment by keithamus** [comment]
I'll close this issue, as we are already aware of it over in the [`type-detect` repo](https://github.com/chaijs/type-detect/issues/98)

**Comment by codler** [comment]
https://github.com/chaijs/type-detect/issues/98#issuecomment-325010785
