### ISSUE TITLE
TypeError: util.addProperty is not a function

### ISSUE THREAD

**Issue by CHYGO1985** [chaijs/chai#1516]
I have tried all the way I know, but the following issue cannot be resolved, so I would like to ask for your advices. Thank you very much in advance.

The app was running well until yesterday, then I add some functions and test cases and I did not add any new dependencies (I have confirmed that by checking the commit history on Github). The tests run good, then I run `npm run dev` or `npm start` , I have the following issue reported typerror from chai (I can still run the tests by `npm run test`).

The things I have tried:
1. search 'TypeError: util.addProperty is not a function' on Google, there is nothing
2. reinstall chai and chai-as-promised
3. delete node_modules and reinstall all dependencies by run `npm i`
4. upgrade node from 18.7.0 to 18.16.0

```
~~/node_modules/chai/lib/chai/assertion.js:94
    util.addProperty(this.prototype, name, fn);
         ^

TypeError: util.addProperty is not a function
    at Assertion.addProperty (~~/node_modules/chai/lib/chai/assertion.js:94:10)
    at ~~/WechatBot_Server/node_modules/chai/lib/chai/core/assertions.js:48:15
    at Array.forEach (<anonymous>)
    at module.exports (~~/node_modules/chai/lib/chai/core/assertions.js:47:46)
    at exports.use 
(~~/node_modules/chai/lib/chai.js:39:5)
    at Object.<anonymous> 
(~~/node_modules/chai/lib/chai.js:71:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)

Node.js v18.16.0
```

my package.json:
```
 "scripts": {
    "start": "node ./bin/www.js",
    "dev": "NODE_ENV=dev nodemon ./bin/www.js",
    "debug": "NODE_ENV=dev node --inspect ./bin/www.js",
    "test": "NODE_ENV=test mocha --recursive --exit --timeout 20000",
    "test:unit": "NODE_ENV=test mocha test/unit --recursive --exit --timeout 20000",
    "test:integration": "NODE_ENV=test mocha test/integration --recursive --exit --timeout 20000"
  },
  "dependencies": {
    "app-root-path": "^3.1.0",
    "axios": "^1.3.5",
    "bcrypt": "^5.1.0",
    "chatgpt": "^5.1.3",
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "crypto": "^1.0.1",
    "debug": "~2.6.9",
    "dotenv": "^16.0.3",
    "express": "~4.16.1",
    "handlebars": "^4.7.7",
    "hirestime": "^7.0.3",
    "http-errors": "~1.6.3",
    "ioredis": "^5.3.2",
    "jade": "~1.11.0",
    "jsonwebtoken": "^9.0.0",
    "lodash": "^4.17.21",
    "mint-filter": "^4.0.2",
    "mongoose": "^7.0.0",
    "morgan": "~1.9.1",
    "nodemailer": "^6.9.1",
    "nodemon": "^2.0.21",
    "openai": "^3.2.1",
    "path": "^0.12.7",
    "readline": "^1.3.0",
    "redis": "^4.6.4",
    "redlock": "^5.0.0-beta.2",
    "remark": "^14.0.2",
    "strip-markdown": "^5.0.0",
    "supertest": "^6.3.3",
    "swagger-ui-express": "^4.6.2",
    "winston": "^3.8.2",
    "winston-mongodb": "^5.1.1"
  },
  "devDependencies": {
    "chai": "^4.3.7",
    "chai-as-promised": "^7.1.1",
    "eslint": "^8.34.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0"
  }
```

Any idea of what should I do to further troubleshoot? Thank you again

**Comment by CHYGO1985** [comment]
okay, I think the issue came from I accidently add `import { expectTypes } from 'chai/lib/chai/utils/index.js'` in one of the non test js file

**Comment by koddsson** [comment]
Sounds like this is resolved then? Reopen if not!
