### ISSUE TITLE
@types/chai seems not to be adapted to version 5.0.0

### ISSUE THREAD

**Issue by dhjnam** [chaijs/chai#1578]
`import chai from 'chai'` does not work with chai version 5.0.0.

```javascript
// test.spec.ts
import chai from 'chai';
chai
```

and executing

```bash
ts-mocha ./test.spec.ts"
```

Raises the following error

```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module <project-root>/node_modules/chai/chai.js from <project-root>/test.spec.ts not supported.
Instead change the require of chai.js in <project-root>/test.spec.ts to a dynamic import() which is available in all CommonJS modules.

at Object.<anonymous> (<project-root>/test.spec.ts:6:32)
at m._compile (<project-root>/node_modules/ts-mocha/node_modules/ts-node/dist/index.js:327:29)
at require.extensions.<computed> [as .ts] (<project-root>/node_modules/ts-mocha/node_modules/ts-node/dist/index.js:329:16)
at <project-root>/node_modules/mocha/lib/mocha.js:414:36
at Array.forEach (<anonymous>)
at Mocha.loadFiles (<project-root>/node_modules/mocha/lib/mocha.js:411:14)
at Mocha.run (<project-root>/node_modules/mocha/lib/mocha.js:972:10)
at Object.run (<project-root>/node_modules/mocha/lib/cli/watch-run.js:263:22)
at FSWatcher.<anonymous> (<project-root>/node_modules/mocha/lib/cli/watch-run.js:184:14)
```

Other imports work fine.

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "composite": true,
    "target": "ES6",
    "module": "Node16",
    "rootDir": "./",
    "moduleResolution": "Node16",
    "typeRoots": [
      "./node_modules/@types/",
    ],
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,                
    "outDir": "./dist/",
    "declarationDir": "./dist/@types",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
  },
}
```

`package.json`:
```json
{
  "name": "chai5",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ts-mocha test.spec.ts"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/chai": "^4.3.11",
    "@types/mocha": "^10.0.6",
    "chai": "^5.0.0",
    "mocha": "^10.2.0",
    "ts-mocha": "^10.0.0",
    "typescript": "^5.3.3"
  }
}

```

**Comment by 43081j** [comment]
This is because the project is esm only now.

As the error message says, you would have to use a dynamic import to import it since you're in a commonjs project.

Your package.json doesn't have `type: "module"`, so typescript (with `node16`/`nodenext` resolution) will detect your project as commonjs and parse it as such.

I have an example here:
https://gist.github.com/43081j/78ce1392abb5043b02a29355006880a5

if you're unable to make your project ESM-only, you will have to use a dynamic import (`const chai = await import('chai')`), or stick to 4.x until you're able to migrate forward.

We're still publishing 4.x versions for security etc.

**Comment by 43081j** [comment]
for now (maybe permanently, depending on the outcome of 1569), you can do:

```ts
await import("chai").then((result) =>
  chai = result.use(chaiHttp);
});
```

**Comment by caiosantos10** [comment]
You can try import just methods from 'chai' like this:

`import { use, expect } from 'chai';`
`import chaiHttp from 'chai-http';`
`const chai = use(chaiHttp);`

**Comment by melroyvandenberg** [comment]
I can't take it anymore with Chai + Cha-http with ESM (even when not using TS, but just JS). 

It just impossible to import those two libs. I get `SyntaxError: The requested module 'chai' does not provide an export named 'request'` and if I use `import * as chai from 'chai` to allow me to use `chai.request` I now get: `TypeError: chai.request is not a function`

**Comment by caiosantos10** [comment]
> I can't take it anymore with Chai + Cha-http with ESM (even when not using TS, but just JS).
> 
> It just impossible to import those two libs. I get `SyntaxError: The requested module 'chai' does not provide an export named 'request'` and if I use `import * as chai from 'chai` to allow me to use `chai.request` I now get: `TypeError: chai.request is not a function`

You can try this way:

`import chaiHttp from 'chai-http';`
`const chai = use(chaiHttp);`

and then call:

`chai.request()`

**Comment by melroyvandenberg** [comment]
Ow so `use` returns a new object?.. interesting! Thanks.  I still believe chai should improve this ESM import / usage.

**Comment by 43081j** [comment]
yes, `use` returns an extended chai

```ts
import {use} from 'chai';
import chaiHttp from 'chai-http';

const chai = use(chaiHttp);
```

we have an issue open to investigate if there's any way we can improve this pattern

**Comment by melroyvandenberg** [comment]
Today I suffer again with the same problem but this time just using plain ES6 javascript (no typescript): `TypeError: chai.request is not a function`.

Yes my code looks like this (I removed the should & expect import for clarity):


```js
import { use } from 'chai'
import chaiHttp from 'chai-http'
import app from '../src/index.js'

const chai = use(chaiHttp)

// ... some it(... ) test.... And then:
chai.request(app) // <-- this line is failing still!!
      .get("/example")
```

**Comment by khawaja-h3** [comment]
This is what I did: 
`
process.env.NODE_ENV = "test";

import chaiHttp from "chai-http";
import app from "../main.js";
import * as chai from "chai";
const should = chai.should();
const expect = chai.expect;
const use = chai.use;

const request = use(chaiHttp).request.execute;
describe("/First Test Collection", () => {
  it("test default API welcome route...", (done) => {
    request(app)
      .get("/") // Endpoint to test
      .end((err, res) => {
        res.should.have.status(200); // Check status code
        res.body.should.be.a("object");
        done(); // Signal async completion
      });
  });

  it("expects two values to be equal....", () => {
    // given
    let expectedValue = 10; // when
    let actualValue = 5;
    expect(actualValue).not.to.equal(expectedValue); // then
  });
`});
`

**Comment by khawaja-h3** [comment]
`process.env.NODE_ENV = "test";

import chaiHttp from "chai-http";
import app from "../main.js";
import * as chai from "chai";
const should = chai.should();
const expect = chai.expect;
const use = chai.use;

const request = use(chaiHttp).request.execute;
describe("/First Test Collection", () => {
  it("test default API welcome route...", (done) => {
    request(app)
      .get("/") // Endpoint to test
      .end((err, res) => {
        res.should.have.status(200); // Check status code
        res.body.should.be.a("object");
        done(); // Signal async completion
      });
  });

  it("expects two values to be equal....", () => {
    // given
    let expectedValue = 10; // when
    let actualValue = 5;
    expect(actualValue).not.to.equal(expectedValue); // then
  });
});
`

**Comment by khawaja-h3** [comment]
`import * as bob from "chai"`

**Comment by khawaja-h3** [comment]
This worked for me:
```javascript
process.env.NODE_ENV = "test";

import chaiHttp from "chai-http";
import app from "../main.js";
import * as chai from "chai";
const should = chai.should();
const expect = chai.expect;
const use = chai.use;

const request = use(chaiHttp).request.execute;
describe("/First Test Collection", () => {
  it("test default API welcome route...", (done) => {
    request(app)
      .get("/") // Endpoint to test
      .end((err, res) => {
        res.should.have.status(200); // Check status code
        res.body.should.be.a("object");
        done(); // Signal async completion
      });
  });

  it("expects two values to be equal....", () => {
    // given
    let expectedValue = 10; // when
    let actualValue = 5;
    expect(actualValue).not.to.equal(expectedValue); // then
  });
});

```

**Comment by 43081j** [comment]
the types seem to be right at this time

if someone thinks they're not, please share a reproduction and we can reopen this
