### ISSUE TITLE
Can't install: npm http 404 https://registry.npmjs.org/chia

### ISSUE THREAD

**Issue by themightywrighty** [chaijs/chai#568]
I can't seem to install Chai.

https://registry.npmjs.org/chia is returning 404.  
```
mwright sodium ~/test/mocha $ npm install chia
npm WARN package.json mocha@0.0.0 No repository field.
npm WARN package.json mocha@0.0.0 No README data
npm http GET https://registry.npmjs.org/chia
npm http 404 https://registry.npmjs.org/chia
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "chia"
npm ERR! cwd /home/mwright/test/mocha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mwright/test/mocha/npm-debug.log
npm ERR! not ok code 0
```

**Comment by T1st3** [comment]
There is a typo in the package you want to install ("chia" instead of "chai")

**Comment by keithamus** [comment]
Thanks for the issue @themightywrighty.

Ass @T1st3 points out - it looks like you're trying to install ch**ia** (as in the seeds) and you want ch**ai** (as in the tea).

I'll close this - but if you're still having trouble let me know and we can reopen it :smile:

**Comment by themightywrighty** [comment]
Oh, I am silly. Thank you.
