### ISSUE TITLE
chai.expect doesn't work as expected

### ISSUE THREAD

**Issue by ivanbtrujillo** [chaijs/chai#754]
Hi all,

I'm using Chai ^3.5.0 and seems that chai.expect doesn't working as expected. This is a simple example:
```
  it('1 is equal to 1', () => {
    expect(1).toEqual(1);
  });
```

Test result: 
```

TypeError: expect(...).toEqual is not a function
      at Context.<anonymous> (test.js:90:15)
``` 

I've used assert to test a case, and I wrote the same case with chai.expect. With assert works perfectly but witch chai.expect doesn't work:

```
  it('Should return the initial state (Assert)', function(done) {
    const initialstate = reducer(undefined, {}).toString();
    assert( initialstate == { all: [] }, 'Initial state is equal to { all: [] }');
    done();
  });

  it('Should return the initial state (Chai.expect) ', () => {
    const initialstate = reducer(undefined, {}).toString();
    expect(initialstate).toEqual({ all: [] });
  });
```

The result of tests:
```
List reducer
    ✓ Should return the initial state (Assert)
    1) Should return the initial state (Chai.expect)
    2) 1 is equal to 1


  1 passing (157ms)
  2 failing

  1) List reducer Should return the initial state (Chai.expect) :
     TypeError: expect(...).toEqual is not a function
      at Context.<anonymous> (test.js:86:26)

  2) List reducer 1 is equal to 1:
     TypeError: expect(...).toEqual is not a function
      at Context.<anonymous> (test.js:90:15)

```

Any idea if it's a bug or i need something?

**Comment by meeber** [comment]
Hi @ivanbtrujillo. Please check out http://chaijs.com/guide/styles/ for the differences between the TDD style of assertions using `assert` and the BDD style using `expect` or `should`.

```js
expect(1).to.equal(1);
```

**Comment by ivanbtrujillo** [comment]
Many thanks!
