### ISSUE TITLE
Impossible to expect a function to throw a Type of Error

### ISSUE THREAD

**Issue by Guzim** [chaijs/chai#931]
Hello, 

Here is my code : 
```
class Impact {
  constructor(varX, varY) {
    this.x = 1
    this.y = 1
    try {
      if (('number' === typeof varX) && ('number' === typeof varY)) {
        this.x = varX
        this.y = varY
      }
      else {
        throw new TypeError('Bad type for impact coordinates')
      }
      ...
```
The test associated to it
```
describe ("Impact", () => {
  it("has positive coordinates", () => {
    // Encapsulate the new
    var myFunc = function() { new Impact('a', 4)}
    chai.expect(myFunc).to.throw(TypeError)
    ...
```
The result is  : 
```
  Impact
    1) has positive coordinates
  1 failing

  1) Impact has positive coordinates:
     AssertionError: expected [Function: myFunc] to throw TypeError
      at Context.it (test\impact-test.js:11:33)
```
So .... I would like to have this test succeed. 
How can I deal with it ?

**Comment by keithamus** [comment]
@Guzim thanks for the issue.

This looks like it would work fine, except in your constructor which has `try {` but I can't see the rest of what that does. Unless your constructor actually throws, then the assertion can't catch the error. If your constructor throws, but subsequently catches the error and doesn't rethrow, then chai can't see it.

I'm going to close this issue for now just to clean up our issue tracker, if you aren't able to solve your problem with the above though, feel free to comment here and we can discuss further.

**Comment by Guzim** [comment]
Here is my full code :
```
const constants = require ('../lib/constants')
class Impact {
  constructor(varX, varY) {
    this.x = 1
    this.y = 1
    try {
      if (('number' === typeof varX) && ('number' === typeof varY)) {
        this.x = varX
        this.y = varY
      }
      else {
        throw new TypeError('Bad type for impact coordinates')
      }

      if ((this.x > constants.GRID_SIZE) || (this.y > constants.GRID_SIZE) ||
          (this.x < 1) || (this.y < 1)) {
            throw new RangeError ('Impact out of bound')
      }
    } catch (constructorError) {
      /*
      console.log(constructorError.message);      // "null has no properties"
      */
    }
  }
```

And for the test :
```
const chai = require('chai')
const constants = require('../lib/constants')
const Impact = require('../lib/impact')

var impact1 = new Impact(7, 2)
var impact2 = new Impact(15, 14)
describe ("Impact", () => {
  it("has positive coordinates", () => {
    // Encapsulate the new
    var myFunc = function() { new Impact('a', 4)}
    chai.expect(myFunc).to.throw(TypeError)
    //myFunc = function(){new Impact(1, 3.14)}

    //chai.expect(new Impact(1, 3.14)).to.throw(TypeError)
  })
  it("has no overreach square", ()=> {
    //chai.expect(new Impact(1, constants.GRID_SIZE+1)).to.throw(RangeError)
    //chai.expect(new Impact(constants.GRID_SIZE+1, 1)).to.throw(RangeError)
  })
  it("must be distant from the other point", ()=> {
    var dist = impact1.distance(impact2)
    chai.expect(dist).to.equal(20)
  })
})
```
The exact output for my tests are : 

```
 target-rpg@1.0.0 test C:\Users\Léa\Documents\NodeJS\cibles-system
> mocha



Serve is listening
  Impact
    1) has positive coordinates
    √ has no overreach square
    √ must be distant from the other point

  Server
    √ Up and running

  Target
    √ has a name
    √ has an image for backround
    √ has a square image for background
    - has at least one zone
    - zones must be strictely distincts


  6 passing (118ms)
  2 pending
  1 failing

  1) Impact has positive coordinates:
     AssertionError: expected [Function: myFunc] to throw TypeError
      at Context.it (test\impact-test.js:11:33)



npm ERR! Test failed.  See above for more details.
```


I would like to thank you for being so prompt to answer.
