### ISSUE TITLE
assert.throws(function, Error) fails for ES6 classes

### ISSUE THREAD

**Issue by cowwoc** [chaijs/chai#933]
version 3.5.0

Given:

```
assert.throws(function()
{
	throw new IllegalArgumentException("this is my message");
}, IllegalArgumentException);
```

fail if `IllegalArgumentException` is defined as:

```
class IllegalArgumentException extends Error {
}
```

but succeeds if it is defined as:

```
function IllegalArgumentException(message)
{
	this.message = message;
	// Use V8's native method if available, otherwise fallback
	if ("captureStackTrace" in Error)
		Error.captureStackTrace(this, IllegalArgumentException);
	else
	{
		Object.defineProperty(this, "stack", {
			value: (new Error(message)).stack
		});
	}
}

IllegalArgumentException.prototype = Object.create(Error.prototype);
IllegalArgumentException.prototype.name = "IllegalArgumentException";
IllegalArgumentException.prototype.constructor = IllegalArgumentException;
```

In the case of ES6, the assert fails with:

````
[00:42:50] AssertionError: expected [Function] to throw 'IllegalArgumentException' but 'Error: this is my message' was thrown
  at Assertion.assertThrows  <node_modules\intern\browser_modules\chai\chai.js:1607:14>
  at Assertion.ctx.(anonymous function) [as throw]  <node_modules\intern\browser_modules\chai\chai.js:4192:25>
  at Function.assert.throws  <node_modules\intern\browser_modules\chai\chai.js:3271:52>
  at Test.isNotNull_CustomException [as test]  <build\test\unit\ObjectTest.js:188:25>
  at <node_modules\intern\lib\Test.js:191:24>
  at <node_modules\intern\browser_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <node_modules\intern\browser_modules\dojo\Promise.ts:11:11>
  at <node_modules\intern\browser_modules\dojo\Promise.ts:317:4>
  at run  <node_modules\intern\browser_modules\dojo\Promise.ts:237:7>
  at <node_modules\intern\browser_modules\dojo\nextTick.ts:44:3>
```

**Comment by cowwoc** [comment]
Sorry, false alarm. I noticed that the code was actually undergoing transpiling by Babel prior to executing. The class got transformed to:
```
var IllegalArgumentException = function (_Error) {
	_inherits(IllegalArgumentException, _Error);

	function IllegalArgumentException() {
		_classCallCheck(this, IllegalArgumentException);

		return _possibleConstructorReturn(this, (IllegalArgumentException.__proto__ || Object.getPrototypeOf(IllegalArgumentException)).apply(this, arguments));
	}

	return IllegalArgumentException;
}(Error);
```

so that `throw new IllegalArgumentException()` actually ended up returning an `Error` not a `IllegalArgumentException`. I then ran across this plugin: https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend

Installing it fixed the problem (tests pass). The transpiled code now looks like this:

```
var IllegalArgumentException = function (_extendableBuiltin2) {
	_inherits(IllegalArgumentException, _extendableBuiltin2);

	function IllegalArgumentException() {
		_classCallCheck(this, IllegalArgumentException);

	return _possibleConstructorReturn(this, (IllegalArgumentException.__proto__ || Object.getPrototypeOf(IllegalArgumentException)).apply(this, arguments));
	}

	return IllegalArgumentException;
}(_extendableBuiltin(Error));
```
